# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hava < Formula
  desc "hava is a Go CLI tool to interact with app.hava.io platform."
  homepage "https://github.com/carljavier/hava"
  version "0.0.3-beta"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/carljavier/hava/releases/download/0.0.3-beta/hava_Darwin_x86_64.tar.gz"
      sha256 "76047a76b6424e2f4673180f1509f06356a3fb68e7557a1f97cfacd73e517a9d"

      def install
        bin.install "hava"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/carljavier/hava/releases/download/0.0.3-beta/hava_Darwin_arm64.tar.gz"
      sha256 "8220afce049a3829db69173233315d902b10750959e983368b5075549a3cf1a6"

      def install
        bin.install "hava"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/carljavier/hava/releases/download/0.0.3-beta/hava_Linux_arm64.tar.gz"
      sha256 "6c0ed64e13ce79731c45b24a60210ac90a3079832220d112ac0f54933ca6dd9c"

      def install
        bin.install "hava"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/carljavier/hava/releases/download/0.0.3-beta/hava_Linux_x86_64.tar.gz"
      sha256 "b329592ca5d14585b023ada303a0fe7151e3b22c5eac1d3b97070715af45fcd1"

      def install
        bin.install "hava"
      end
    end
  end
end
